/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Thu Nov 22 21:40:46 2018. */

#include "sample.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t tobalr_testmessage_fields[4] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, tobalr_testmessage, temperature, temperature, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, tobalr_testmessage, humidity, temperature, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, tobalr_testmessage, batteryVoltage, humidity, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
